---
custom_categories:
- name: Protocols
  children:
  - Monitor
- name: Base Monitor Classes
  children:
  - BaseMonitor
  - BaseNotificationMonitor
- name: Application Monitor Classes
  children:
  - ApplicationStateMonitor
  - BackgroundRefreshMonitor
  - MemoryMonitor
  - ProtectedDataMonitor
  - ScreenshotMonitor
  - StatusBarMonitor
  - TimeMonitor
- name: Device Monitor Classes
  children:
  - BatteryMonitor
  - OrientationMonitor
  - ProximityMonitor
- name: Other Monitor Classes
  children:
  - KeyboardMonitor
